// <auto-generated />
using MainActivity.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace MainActivity.Migrations {
    [DbContext(typeof(PrimeDbContext))]
    partial class PrimeDbContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("MainActivity.Models.Administrator", b => {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Email")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<string>("Password")
                    .HasColumnType("TEXT");

                b.Property<string>("Role")
                    .HasColumnType("TEXT");

                b.HasKey("ID");

                b.ToTable("Administrators");
            });

            modelBuilder.Entity("MainActivity.Models.ArticleContent", b => {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ParagraphContent")
                    .HasColumnType("TEXT");

                b.Property<string>("ParagraphTitle")
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .HasColumnType("TEXT");

                b.HasKey("ID");

                b.ToTable("ArticleContents");
            });
#pragma warning restore 612, 618
        }
    }
}
